### ISSUE TITLE
RDS for Mysql やAuroraでの実行について

### ISSUE THREAD

**Issue by Twinuma** [winebarrel/gratan#26]
Auroraインスタンスに対して、
```
gratan -a --dry-run --host DB_HOST--username username --password password
```
を実行すると、
```
[ERROR] Access denied; you need (at least one of) the SUPER privilege(s) for this operation
````
となります。

実行ユーザはrootユーザになります。
AuroraやRDSのDBユーザを管理したい場合は、どのようにすればよいでしょうか？

**Comment by nao23** [comment]
@Twinuma 
おそらくですが、バイナリロギングを無効にしようとするところでSUPER権限が足りなくて怒られるのだと思います。(`--debug` を付けると、実行しているSQL文が見れます)

バイナリロギングの設定を変更するためにはSUPER権限が必要なのですが、AWS RDSでは`rdsadmin`というユーザ(RDSを立てた時に最初から作られているユーザ) しかSUPER権限を持っていません。
https://dev.mysql.com/doc/refman/5.6/ja/set-sql-log-bin.html

従って、rootユーザではバイナリロギングを無効にできないので、 `--skip-disable-log-bin` というオプションで、この処理をskipさせると実行できるようになるかと思います。

**Comment by Twinuma** [comment]
@nao23 ありがとうございます！教えて頂いたコマンドで確認してみますね！

**Comment by Twinuma** [comment]
@nao23 
誠にありがとうございました。教えて頂いた内容で実行できました！
デバッグで確かにバイナリロギングを無効にしようとしてましたね。

とてもいいアプリケーションを作成していただきありがとうございます 😄 
```
$ gratan -a --dry-run --host <host> --username <username> --password <password> --debug
Apply `Grantfile` to {"host":"<host>","username":"<username>","port":3306} (dry-run)
[DEBUG] SET SQL_LOG_BIN = 0
Traceback (most recent call last):
	10: from /opt/rbenv/versions/2.6.3/bin/gratan:23:in `<main>'
	 9: from /opt/rbenv/versions/2.6.3/bin/gratan:23:in `load'
	 8: from /opt/rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/gratan-0.3.2/bin/gratan:152:in `<top (required)>'
	 7: from /opt/rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/gratan-0.3.2/lib/gratan/client.rb:61:in `apply'
	 6: from /opt/rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/gratan-0.3.2/lib/gratan/client.rb:247:in `in_progress'
	 5: from /opt/rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/gratan-0.3.2/lib/gratan/driver.rb:208:in `disable_log_bin_local'
	 4: from /opt/rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/gratan-0.3.2/lib/gratan/driver.rb:228:in `query'
	 3: from /opt/rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
	 2: from /opt/rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
	 1: from /opt/rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
/opt/rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `_query': Access denied; you need (at least one of) the SUPER privilege(s) for this operation (Mysql2::Error)

$ gratan -a --dry-run --host <host> --username <username> --password <password> --debug --skip-disable-log-bin
Apply `Grantfile` to {"host":"<host>","username":"<username>","port":3306} (dry-run)
[DEBUG] SELECT user, host FROM mysql.user
[DEBUG] SHOW GRANTS FOR 'auditor'@'%'
[DEBUG] SHOW GRANTS FOR 'new_master_user'@'%'
[DEBUG] SHOW GRANTS FOR 'rootmaster'@'%'
[DEBUG] SHOW GRANTS FOR 'rdsadmin'@'localhost'
GRANT USAGE ON *.* TO 'foo'@'%' IDENTIFIED BY PASSWORD '*F2F68D0BB27A773C1D944270E5FAFED515A3FA40' (dry-run)
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, ALTER, LOCK TABLES, CREATE VIEW, SHOW VIEW, TRIGGER ON *.* TO 'foo'@'localhost' IDENTIFIED BY PASSWORD '*F2F68D0BB27A773C1D944270E5FAFED515A3FA40' (dry-run)
FLUSH PRIVILEGES (dry-run)
No change

$ gratan -a --host <host> --username <username> --password <password> --debug --skip-disable-log-bin
Apply `Grantfile` to {"host":"<host>","username":"<username>","port":3306}
[DEBUG] SELECT user, host FROM mysql.user
[DEBUG] SHOW GRANTS FOR 'auditor'@'%'
[DEBUG] SHOW GRANTS FOR 'new_master_user'@'%'
[DEBUG] SHOW GRANTS FOR 'rootmaster'@'%'
[DEBUG] SHOW GRANTS FOR 'rdsadmin'@'localhost'
GRANT USAGE ON *.* TO 'foo'@'%' IDENTIFIED BY PASSWORD '*F2F68D0BB27A773C1D944270E5FAFED515A3FA40'
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, ALTER, LOCK TABLES, CREATE VIEW, SHOW VIEW, TRIGGER ON *.* TO 'foo'@'localhost' IDENTIFIED BY PASSWORD '*F2F68D0BB27A773C1D944270E5FAFED515A3FA40'
FLUSH PRIVILEGES
```
